# fly.toml app configuration file generated for bloglist-frontend-holy-hill-1927 on 2025-09-26T15:07:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglist-frontend-holy-hill-1927'
primary_region = 'arn'

[build]


[env]
  PORT = "3003"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
